version: "3"
services:
  web:
    image: gabrielrf777/arena3-api:1.0
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - networkName

volumes:
  data:
