version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: arena3-image
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
